import { MutationOption, Season } from "@/lib/types";

export const TURN_PER_YEAR = 12;

export const SEASON_BY_MONTH: Season[] = [
  "spring",
  "spring",
  "spring",
  "summer",
  "summer",
  "summer",
  "fall",
  "fall",
  "fall",
  "winter",
  "winter",
  "winter",
];

export const BIOMASS_GROWTH_BY_TYPE = {
  water: 0,
  grass: 7,
  woods: 5,
  desert: 2,
  marsh: 9,
} as const;

export const SEASON_GROWTH_MULTIPLIER: Record<Season, number> = {
  spring: 1.4,
  summer: 1.2,
  fall: 0.9,
  winter: 0.4,
};

export const SEASON_EVAPORATION: Record<Season, number> = {
  spring: 0.8,
  summer: 1.3,
  fall: 0.7,
  winter: 0.3,
};

export const HEX_COLORS = {
  water: "#2563eb",
  grass: "#16a34a",
  woods: "#166534",
  desert: "#eab308",
  marsh: "#15803d",
} as const;

export const MUTATION_OPTIONS: MutationOption[] = [
  {
    id: "long_legs",
    name: "Long Legs",
    description: "Escape-focused morphology.",
    plus: "+20% escape chance from predators.",
    minus: "+15% food consumption.",
    cost: 2,
    diet: "herbivore",
    effects: {
      baseSpeed: 0.45,
      stamina: 0.35,
      baseMetabolism: 0.9,
    },
  },
  {
    id: "big_ears",
    name: "Big Ears",
    description: "Early predator detection.",
    plus: "Detects predators 2 hexes away.",
    minus: "+10% chance to be spotted.",
    cost: 2,
    diet: "herbivore",
    effects: {
      awareness: 1,
      baseMetabolism: 0.4,
      baseSpeed: -0.15,
      stealth: -0.15,
    },
  },
  {
    id: "thick_fur",
    name: "Thick Fur",
    description: "Cold-weather adaptation.",
    plus: "Survival bonus in winter.",
    minus: "Rapid energy loss in summer/desert.",
    cost: 2,
    diet: "herbivore",
    effects: {
      coldTolerance: 1.4,
      heatTolerance: -1.1,
      baseMetabolism: 0.45,
      defense: 0.2,
    },
  },
  {
    id: "ruminant_stomach",
    name: "Ruminant Stomach",
    description: "Digest bark/twigs from woods.",
    plus: "Can consume woods biomass.",
    minus: "Moves 1 hex slower.",
    cost: 3,
    diet: "herbivore",
    effects: {
      foragingEfficiency: 1.1,
      stamina: -0.45,
      baseMetabolism: -0.25,
    },
  },
  {
    id: "high_fecundity",
    name: "High Fecundity",
    description: "More offspring per reproduction event.",
    plus: "Produces 2 offspring.",
    minus: "Offspring start with 50% energy.",
    cost: 3,
    diet: "herbivore",
    effects: {
      fecundity: 1.4,
      defense: -0.2,
      stamina: -0.2,
      maxAge: -4,
    },
  },
  {
    id: "herd_instinct",
    name: "Herd Instinct",
    description: "Defensive grouping and shared vigilance.",
    plus: "Nearby allies improve detection and escape odds.",
    minus: "Crowds consume local biomass faster.",
    cost: 3,
    diet: "herbivore",
    effects: {
      awareness: 0.65,
      defense: 0.45,
      fecundity: 0.25,
      foragingEfficiency: -0.15,
    },
  },
  {
    id: "horned_defense",
    name: "Horned Defense",
    description: "Heavy impact defense against attackers.",
    plus: "Predators need more attack power to secure a kill.",
    minus: "Extra mass slows escape.",
    cost: 3,
    diet: "herbivore",
    effects: {
      defense: 1.1,
      attackPower: 0.45,
      baseSpeed: -0.25,
      baseMetabolism: 0.4,
    },
  },
  {
    id: "sure_footing",
    name: "Sure Footing",
    description: "Stable movement across marsh and woods.",
    plus: "Less movement loss in rough terrain.",
    minus: "Slightly lower top speed in open sprints.",
    cost: 2,
    diet: "herbivore",
    effects: {
      stamina: 0.7,
      defense: 0.35,
      baseSpeed: -0.1,
    },
  },
  {
    id: "ambush_camo",
    name: "Ambush Camo",
    description: "Stealth hunting in woods.",
    plus: "Hidden in woods hexes.",
    minus: "-50% catch rate in grass.",
    cost: 2,
    diet: "carnivore",
    effects: {
      stealth: 1,
      attackPower: 0.35,
      baseSpeed: -0.15,
    },
  },
  {
    id: "pack_hunter",
    name: "Pack Hunter",
    description: "Cooperative hunting behavior.",
    plus: "+10% kill chance per ally.",
    minus: "Requires 2x total biomass.",
    cost: 3,
    diet: "carnivore",
    effects: {
      awareness: 0.45,
      attackPower: 0.55,
      fecundity: 0.15,
      baseMetabolism: 0.4,
    },
  },
  {
    id: "venomous_bite",
    name: "Venomous Bite",
    description: "Take down larger prey.",
    plus: "Can kill larger prey.",
    minus: "2-turn cooldown after a kill.",
    cost: 3,
    diet: "carnivore",
    effects: {
      attackPower: 0.95,
      stealth: 0.2,
      baseMetabolism: 0.45,
    },
  },
  {
    id: "apex_size",
    name: "Apex Size",
    description: "Top-of-chain body plan.",
    plus: "Cannot be killed by other predators.",
    minus: "Slow and starves 20% faster.",
    cost: 4,
    diet: "carnivore",
    effects: {
      size: 0.6,
      attackPower: 1.1,
      defense: 0.8,
      baseSpeed: -0.35,
      baseMetabolism: 1,
      fecundity: -0.5,
    },
  },
  {
    id: "keen_smell",
    name: "Keen Smell",
    description: "Tracks prey and carrion through nearby hexes.",
    plus: "Better target selection and carrion recovery.",
    minus: "Extra sensory upkeep.",
    cost: 2,
    diet: "carnivore",
    effects: {
      awareness: 1,
      foragingEfficiency: 0.85,
      baseMetabolism: 0.35,
    },
  },
  {
    id: "sprint_burst",
    name: "Sprint Burst",
    description: "Explosive short-window chase speed.",
    plus: "Stronger closing speed on open ground.",
    minus: "More fatigue after failed chases.",
    cost: 3,
    diet: "carnivore",
    effects: {
      baseSpeed: 0.6,
      attackPower: 0.55,
      stamina: -0.55,
      baseMetabolism: 0.75,
    },
  },
  {
    id: "crushing_jaws",
    name: "Crushing Jaws",
    description: "Trades agility for raw bite force.",
    plus: "Breaks through defended prey.",
    minus: "Slower attack setup and movement.",
    cost: 3,
    diet: "carnivore",
    effects: {
      attackPower: 1.15,
      defense: 0.2,
      baseSpeed: -0.25,
      baseMetabolism: 0.55,
    },
  },
  {
    id: "scavenger_gut",
    name: "Scavenger Gut",
    description: "Stable nutrition from leftover kills.",
    plus: "Consumes carrion more efficiently.",
    minus: "Lower peak hunting pressure.",
    cost: 2,
    diet: "carnivore",
    effects: {
      foragingEfficiency: 1.1,
      attackPower: -0.35,
      baseMetabolism: -0.2,
      coldTolerance: 0.2,
    },
  },
];
